name: environment_config
description: Environment specific config generator. Allows to specify env configuration during CI/CD build. Primarily created to simplify Flutter build configuration
version: 2.2.3
homepage: https://github.com/TatsuUkraine/dart_environment_config
repository: https://github.com/TatsuUkraine/dart_environment_config
issue_tracker: https://github.com/TatsuUkraine/dart_environment_config/issues

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  dart_style: ">=1.0.0 <2.0.0"
  code_builder: ">=3.0.0 <4.0.0"
  args: ">=1.0.0 <2.0.0"
  yaml: ">=2.0.0 <3.0.0"
  build: ">=1.3.0"
  source_gen: ">=0.9.5"
